const codes = [
  "Bros before Hoes – A ‘Hoe’ is defined as any woman that is not your wife or direct family.", "A Bro is always allowed to do something stupid as long as his Bros are doing it.", "If a Bro gets a dog it must be at least knee height when fully grown.", "Whether a Bro is in to sports or not they pick a team and support them until their dying breath.", "A Bro shall not gaze at a naked Bro.", "A Bro never sends a birthday card to another Bro.", "A Bro is honor-bound to aid his Bros with DIY and moving house.", "Bros do not share dessert.", "If a Bro leads a beer/food run they are entitled to all left over change.",
  "A Bro doesn’t allow another Bro to get married until they are at least thirty years old.",
  "A Bro never dances with their hands above their head.",
  "A Bro will not sleep with another Bro's sister. However, a Bro is allowed to be vocal about her level of attractiveness.",
  "A Bro shall not wear his cell phone on a belt clip.",
  "Bros don't make eye-contact during a Devil's Three-way.",
  "A Bro never rents a chick flick.",
  "Even in a fight to the death a Bro never punches another Bro in the groin.",
  "A Bro never cries.",
  "A Bro never applies sunscreen to another Bro.",
  "A Bro never wears pink underwear.",
  "A Bro never publicly reveals how many people another Bro has slept with.",
  "A Bro is not required to remember another Bro's birthday.",
  "A Bro is required to go out with his Bros on Saint Patrick's Day.",
  "A Bro doesn't grow a moustache.",
  "A Bro will make any and all effort to provide his Bro with a condom when they score.",
  "A Bro must always reciprocate a round of drinks.",
  "A Bro ALWAYS enhances another Bro's job description when introducing him.",
  "A Bro leaves the toilet seat up for his Bros.",
  "If a Bro buys a new car he is required to pop the hood when showing it off to his Bros.",
  "If a Bro for whatever reason needs to drive another Bro's car, they shall not adjust the preprogrammed radio stations.",
  "A Bro shows up to a party with at least one more unit of alcohol than they plan to drink.",
  "Bros start at least one fire a year.",
  "If a Bro asks another Bro to keep a secret he shall take that secret to his grave.",
  "A Bro never wears socks with sandals.",
  "The mum of a Bro is always off-limits.",
  "When a Bro isn't invited to another Bro's wedding, they don't make a big deal about it.",
  "A Bro doesn't sing along to music in a bar.",
  "'Clothing optional' doesn't really mean 'clothing optional' to Bros.",
  "A Bro shall not damage another Bro's chances to score.",
  "A Bro never willingly relinquishes possession of a remote control.",
  "A Bro is never vegan.",
  "If a Bro fails a challenge, it's ALWAYS the equipment's fault.",
  "Every Bro knows a Bro who is the worlds best at something.",
  "When a Bro learns another Bro has been in a traffic accident, they must first ask what condition the car is in.",
  "When hosting, a Bro orders enough pizza for all his Bros.",
  "A Bro shall seek no revenge if they pass out around their Bros and wake up to find their body covered in drawings and shaving foam.",
  "A Bro is never offended if another Bro fails to return a phone call, text or email.",
  "A Bro doesn't listen to chick music... in front of other Bros.",
  "A Bro pretends to understand and enjoy cigars.",
  "It is NEVER acceptable for a Bro to sleep with another Bro's ex.",
  "Bros don't quote Oscar Wilde.",
  "A Bro always admits when they farted.",
  "A Bro will always verify another Bro's story when they are trying to score.",
  "If your team beats your Bro's team you have 24 hours to rub it in.",
  "A Bro always takes a piss standing up.",
  "A Bro never catches a cold. Bros are struck down with Man Flu.",
  "If a Bro finds his Bro's girlfriend repulsive, they shall not say anything until they have broken up.",
  "A Bro never gives another Bro the silent treatment.",
  "A Bro always has his Bro's back.",
  "Women can also be a Bro.",
  "A Bro DOES NOT masturbate in front of other Bros.",
  "When a Bro asks another Bro to look after their drink, that Bro never tampers with it. Pranks NEVER involve another Bro's drink.",
  "A Bro doesn't unfriend his Bro on Facebook while in a huff.",
  "All Bros are required to take turns as the 'designated driver'.",
  "Bros don't wax their body hair.",
  "A Bro is not expected to notice another Bro's new haircut.",
  "A Bro never asks another Bro to come with them to the bathroom.",
  "A Bro never wears Crocs.",
  "Bros DO NOT pout for selfies.",
  "A Bro never uses another Bro's toothbrush.",
  "Bros don't use umbrellas.",
  "A Bro DOES NOT choose his own nickname. A nickname, good or bad, is bestowed upon you by your fellow Bros.",
  "Bros take care of their fellow bros when they have too much to drink.",
  "A Bro of a Bro is a Bro to you.",
  "When a Bro has a kid his Bros become honorary uncles.",
  "A Bro never keeps a photo of their Bro in his wallet.",
  "A Bro does not allow his Bro to drunk dial or text his ex.",
  "Bros don't wear skinny jeans.",
  "A Bro ALWAYS honours a bet.",
  "A Bro is honour bound to accept all arm wrestling challenges.",
  "Bros pay for their dates.",
  "Bros don't stop to smell flowers.",
  "Bros don't touch another Bro's drink without express permission.",
  "Bros don't break up chick fights until a sufficient amount of clothing has been pulled off.",
  "A Bro will ALWAYS watch a movie narrated by Morgan Freeman.",
  "At a Bro's funeral, all other Bros toast with the deceased's drink of choice.",
  "When a Bro wants to do something stupid, you film it.",
  "A Bro must NEVER impede on a Bro's ability to suit up.",
  "ALL conversations between Bros are subject to 'Bro to Bro confidentiality'.",
  "A bro cannot give another Bro a teddy bear.",
  "Bros shall never under any circumstances go and see a chick flick alone.",
  "A Bro does not dare or challenge another bro to do anything they wouldn't try themselves.",
  "A Bro and a Brother are not the same thing.",
  "A Bro never rearranges the dishes at another Bro's house.",
  "Paint Balling is the ONLY combat scenario in which a Bro's balls are not off limits.",
  "When a Bro leaves his seat that seat becomes vacant and cannot be reclaimed if another Bro takes it.",
  "Bros shall not wear a Fanny Pack/Bum Bag.",
  "A Bro never leaves another Bro behind.",
  "A Bro never makes eye-contact with another Bro while eating a banana.",
  "Dibs cannot be implied, you must call dibs in front of witnesses for any said Dibs to be valid.",
  "When playing or responding to a prank, a Bro's car is off limits.",
  "If you catch your Bro's partner cheating you immediately tell your Bro regardless of any shit-storm that may arise.",
  "A Bro always has a condom in their wallet.",
  "All Bros like steak.",
  "Bros don't take selfies while having a dump.",
  "A Bro never lets his brokenhearted Bro drink alone.",
  "A Bro never tickles another Bro.",
  "A Bro always offers his Bros a drink when getting one for themselves.",
  "Bros wear their pants/trousers above their ass.",
  "Bros don't use a photo of their pet or child as their profile picture.",
  "A Bro doesn't get lost, he merely finds an alternate route.",
  "If a Bro wins a trophy that can be used as a cup they will drink alcohol out of it as soon as possible.",
  "Bros don't giggle.",
  "Bros don't wear turtlenecks.",
  "If Bros share a house/apartment all Bros are obligated to stay out of the way if a fellow Bro brings their date home.",
  "A Bro NEVER under ANY circumstances attempts to get with another Bro's partner.",
  "Bros don't touch each others hair.",
  "When a Bro offers another Bro chewing gum, that offer is for two or more pieces.",
  "Bro's don't smell each other on purpose.",
  "A bro is NEVER afraid to fail.",
  "If a Bro injures themselves while lifting weights, fellow Bros will add more weights before getting help.",
  "Bros do not share a drink or popcorn at the cinema.",
  "Bros only comment on a fellow Bro's fashion choice if that choice will affect their ability to get laid.",
  "All Bros have an interest in some sort of weaponry.",
  "A bro shall never engage in any sexual activity with a Girl-Bro.",
];

(() => {

  for (let i = 0; i < codes.length; i++) {
    codes[i] = {
      number: i + 1,
      content: codes[i],
    };
  }
})();